theme: jekyll-theme-cayman
markdown: kramdown
authors:
  Zhenbang:
    name: Zhenbang Wang
    display_name: Zhenbang
    email: zw11@illinois.edu
    github: kevinzbw
  Zixin:
    name: Zixin Huang
    display_name: Zixin
    email: zixinh2@illinois.edu
    github: yekerr

google_analytics: UA-111576965-2